/** The first-run setup API: what Kith can be connected to, and connecting him.
 *
 * Deliberately separate from `config.ts`. That edits a working setup one field at a
 * time; this one has to try a connection that might be wrong, repeatedly, without
 * saving anything. The shapes here mirror `server/kith/services/connections`.
 */

export type ProviderKind = "openrouter" | "openai" | "ollama";

/** A choice card. Generated by the server from the provider itself, so a new
 *  provider appears here without a change to this file. */
export interface ProviderCard {
  kind: ProviderKind;
  label: string;
  blurb: string;
  requires: string;
  tradeoff: string;
  signupUrl: string;
  listsWithoutKey: boolean;
  needsBaseUrl: boolean;
  needsKey: boolean;
}

/** One model a provider offers. Nulls mean "the provider didn't say" — never a
 *  guessed default, so unknown pricing can't be shown as free. */
export interface ModelOption {
  id: string;
  name: string;
  promptPerMTok: number | null;
  completionPerMTok: number | null;
  /** What a cached prompt token costs to read back, and to put there. Kith caches every
   *  request, so a warm round bills most of its prompt at the read rate — usually a
   *  tenth of input — while a write is 1.25x. Null where the provider does not quote it,
   *  which includes the ones that cache automatically at no extra charge. */
  cacheReadPerMTok: number | null;
  cacheWritePerMTok: number | null;
  context: number | null;
  supportsTools: boolean | null;
  /** Artificial Analysis' agentic index: how well it sustains multi-step tool use.
   *  The most relevant number here, since that is all Kith does. Null where the
   *  provider publishes no measurement, which is most of any catalogue. */
  agenticIndex: number | null;
  codingIndex: number | null;
  /** The weights are published, so the model can outlive whoever serves it. */
  openWeights: boolean;
  /** ISO date the provider intends to withdraw it. */
  retiresOn: string | null;
}

/** Why a model is being recommended. Three kinds of good, not one axis. */
export type Tier = "frontier" | "value" | "open";

/** A recommendation and its evidence. The reason is load-bearing: it lets someone
 *  check the suggestion instead of trusting it. */
export interface Pick {
  tier: Tier;
  modelId: string;
  headline: string;
  reason: string;
}

/** A capability that isn't required, with the cost of its absence. */
export interface ReadinessCheck {
  key: string;
  title: string;
  health: "ok" | "degraded";
  summary: string;
  remedy: string;
}

export interface ConnectionState {
  kind: ProviderKind;
  model: string | null;
  baseUrl: string | null;
  apiKeySet: boolean;
  requiresKey: boolean;
  supportsWebSearch: boolean;
  isComplete: boolean;
}

export interface SetupSnapshot {
  onboarded: boolean;
  connection: ConnectionState;
  providers: ProviderCard[];
  search: { current: SearchState; options: SearchOption[] };
  checks: ReadinessCheck[];
}

export type SearchKind = "searxng" | "openrouter" | "none";

/** One way to search. `available` is false when the option cannot work with the
 *  connection that was just chosen — shown greyed out with a reason, not hidden. */
export interface SearchOption {
  kind: SearchKind;
  label: string;
  blurb: string;
  tradeoff: string;
  requires: string;
  needsUrl: boolean;
  defaultUrl: string;
  available: boolean;
  unavailableBecause: string;
}

export interface SearchState {
  kind: SearchKind;
  searxUrl: string | null;
  endpoint: string | null;
  enabled: boolean;
  costsMoney: boolean;
}

export interface SearchProbeOutcome {
  /** A real search ran and came back with something. */
  working: boolean;
  detail: string;
  hits: number;
}

/** Whether the credential is good — a separate question from reachability, because
 *  OpenRouter's catalogue answers with no key at all. */
export type KeyState = "not_required" | "missing" | "valid" | "rejected";

export interface ProbeOutcome {
  /** We got a model list. Enough to fill the picker, not enough to save. */
  reachable: boolean;
  /** Reached, and holding a credential the provider accepts. Gate "Continue" on this. */
  usable: boolean;
  detail: string;
  models: ModelOption[];
  suggested: Pick[];
  keyState: KeyState;
  /** Remaining credit, or the provider's own words for why it said no. */
  keyDetail: string;
}

export interface Credentials {
  kind: ProviderKind;
  baseUrl?: string;
  /** Omit to reuse the key already stored for this same endpoint. */
  apiKey?: string;
}

export async function fetchSetup(signal?: AbortSignal): Promise<SetupSnapshot> {
  const response = await fetch("/api/setup", { signal });
  if (!response.ok) throw new Error(`/api/setup returned ${response.status}`);
  return (await response.json()) as SetupSnapshot;
}

/** Try a connection. Never throws for a bad key — an unreachable provider is a
 *  normal answer here, carried in `reachable` and `detail`. */
export async function probeConnection(
  input: Credentials,
  signal?: AbortSignal,
): Promise<ProbeOutcome> {
  const response = await fetch("/api/setup/probe", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(input),
    signal,
  });
  const body = (await response.json()) as ProbeOutcome & { error?: string };
  if (!response.ok) throw new Error(body.error ?? `probe failed (${response.status})`);
  return body;
}

/** Save the connection. Rejects with the server's own sentence, which is written
 *  to be shown to the person who caused it. */
export async function completeSetup(
  input: Credentials & { model: string },
): Promise<{ connection: ConnectionState; warnings: string[] }> {
  const response = await fetch("/api/setup/complete", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(input),
  });
  const body = (await response.json()) as {
    connection: ConnectionState;
    warnings: string[];
    error?: string;
  };
  if (!response.ok) throw new Error(body.error ?? `saving failed (${response.status})`);
  return body;
}

/** Try a search provider. Runs one real search server-side and discards the results,
 *  so the answer is whether it works rather than whether the URL parses. */
export async function probeSearch(
  input: { kind: SearchKind; searxUrl?: string },
  signal?: AbortSignal,
): Promise<SearchProbeOutcome> {
  const response = await fetch("/api/setup/search/probe", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(input),
    signal,
  });
  const body = (await response.json()) as SearchProbeOutcome & { error?: string };
  if (!response.ok) throw new Error(body.error ?? `probe failed (${response.status})`);
  return body;
}

export async function saveSearch(input: {
  kind: SearchKind;
  searxUrl?: string;
}): Promise<SearchState> {
  const response = await fetch("/api/setup/search", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(input),
  });
  const body = (await response.json()) as SearchState & { error?: string };
  if (!response.ok) throw new Error(body.error ?? `saving failed (${response.status})`);
  return body;
}

// -- formatting, shared by the picker and the summary ----------------------- //

/** "$0.30" / "free" / "—". Unknown and free must not look alike. */
export function formatPrice(perMTok: number | null): string {
  if (perMTok === null) return "—";
  if (perMTok === 0) return "free";
  if (perMTok < 0.01) return `$${perMTok.toFixed(4)}`;
  return `$${perMTok.toFixed(2)}`;
}

/** "128K" / "1M" / "1.5M" — a token count nobody wants to read in full.
 *
 * The trailing ".0" is stripped after rounding, not before: 1,000,000 and 1,048,576
 * are the same size to a reader, and showing them as "1M" and "1.0M" in adjacent rows
 * looks like a difference that isn't there.
 */
export function formatContext(tokens: number | null): string {
  if (!tokens) return "—";
  if (tokens >= 1_000_000) {
    return `${(tokens / 1_000_000).toFixed(1).replace(/\.0$/, "")}M`;
  }
  return `${Math.round(tokens / 1000)}K`;
}

// -- everything configurable ------------------------------------------------ //

/** One knob, carrying its own documentation so this file needs no second copy. */
export interface Tunable {
  key: string;
  env: string;
  label: string;
  help: string;
  default: number | string | boolean;
  group: string;
  /**
   * `"bool"` was missing from this union while the server had been sending it all along, and
   * that omission was the whole bug: the settings row reads `kind === "text" ? "text" : "number"`,
   * so a boolean fell through to a number input. `String(true)` is not a valid number, so the
   * browser rendered the field empty and showed the placeholder instead — three settings that
   * displayed a greyed-out `true`, indistinguishable from unset, and impossible to type `false`
   * into. Adding the member here is what makes the missing branch a type error.
   */
  kind: "int" | "float" | "text" | "bool";
  min: number | null;
  max: number | null;
  unit: string;
  /**
   * The only accepted values, when there are a handful. Empty means free text.
   *
   * Optional, and it has to be: declaring it `string[]` was correct about the current server and
   * wrong about the running one. A type says what the wire *should* carry and validates nothing —
   * the server on the other end had not been restarted, sent no `choices`, and
   * `knob.choices.length` took the whole settings page down with it. Any field added to this
   * payload is absent for as long as some build is a version behind, which during development is
   * always and after shipping is every upgrade.
   */
  choices?: string[];
  value: number | string | boolean;
  isDefault: boolean;
  /** An environment variable is winning, so editing the field would do nothing. */
  fromEnv: boolean;
}

export interface TunableGroup {
  key: string;
  label: string;
  blurb: string;
  settings: Tunable[];
}

/** A deployment path. Read-only: the databases are open by the time anyone sees this. */
export interface ConfigPath {
  label: string;
  value: string;
  env: string;
  /** What is in it, where the server measured it. */
  bytes?: number;
  entries?: number;
  /** Worth a reveal-in-Finder button — a real folder rather than a build path. */
  open?: boolean;
  /** Somewhere the person gets to choose, not just read. Only his workspace, so far. */
  change?: boolean;
  /** Fixed by an environment variable at launch, so the app cannot override it. */
  pinned?: boolean;
  note?: string;
}

export interface TuningSnapshot {
  groups: TunableGroup[];
  paths: ConfigPath[];
}

export async function fetchTuning(signal?: AbortSignal): Promise<TuningSnapshot> {
  const response = await fetch("/api/tuning", { signal });
  if (!response.ok) throw new Error(`/api/tuning returned ${response.status}`);
  return (await response.json()) as TuningSnapshot;
}

/** Change settings. Values are clamped server-side, so what comes back is what he'll
 *  actually use — which may not be exactly what was sent. */
export async function saveTuning(
  updates: Record<string, number | string | boolean>,
): Promise<TuningSnapshot> {
  const response = await fetch("/api/tuning", {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(updates),
  });
  const body = (await response.json()) as { state: TuningSnapshot; error?: string };
  if (!response.ok) throw new Error(body.error ?? `saving failed (${response.status})`);
  return body.state;
}

export async function resetTuning(keys?: string[]): Promise<TuningSnapshot> {
  const response = await fetch("/api/tuning/reset", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(keys ? { keys } : {}),
  });
  const body = (await response.json()) as TuningSnapshot & { error?: string };
  if (!response.ok) throw new Error(body.error ?? `reset failed (${response.status})`);
  return body;
}

export interface SkillSummary {
  name: string;
  description: string;
  license: string;
  compatibility: string;
  metadata: Record<string, string>;
  allowedTools: string[];
  /** Frontmatter fields from a newer or different tool that Kith does not act on. */
  unsupportedFields: string[];
  bodyChars: number;
  resources: string[];
  path: string;
}

export interface SkillsSnapshot {
  root: string;
  skills: SkillSummary[];
  problems: { name: string; error: string }[];
  /** What the whole set costs in every prompt — names and descriptions only. */
  indexChars: number;
  indexTokens: number;
}

export async function fetchSkills(): Promise<SkillsSnapshot> {
  const response = await fetch("/api/skills");
  if (!response.ok) throw new Error(`/api/skills returned ${response.status}`);
  return (await response.json()) as SkillsSnapshot;
}

/** Install a skill from a folder already on this machine. Nothing is downloaded. */
export async function installSkill(path: string): Promise<SkillSummary> {
  const response = await fetch("/api/skills", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ path }),
  });
  const body = (await response.json()) as SkillSummary & { error?: string };
  if (!response.ok) throw new Error(body.error ?? `install failed (${response.status})`);
  return body;
}

export async function removeSkill(name: string): Promise<void> {
  const response = await fetch(`/api/skills/${encodeURIComponent(name)}`, { method: "DELETE" });
  if (!response.ok) {
    const body = (await response.json().catch(() => ({}))) as { error?: string };
    throw new Error(body.error ?? `couldn't remove it (${response.status})`);
  }
}
