/** The first-run setup API: what Kith can be connected to, and connecting him.
 *
 * Deliberately separate from `config.ts`. That edits a working setup one field at a
 * time; this one has to try a connection that might be wrong, repeatedly, without
 * saving anything. The shapes here mirror `server/kith/services/connections`.
 */

export type ProviderKind = "openrouter" | "openai" | "ollama";

/** A choice card. Generated by the server from the provider itself, so a new
 *  provider appears here without a change to this file. */
export interface ProviderCard {
  kind: ProviderKind;
  label: string;
  blurb: string;
  requires: string;
  tradeoff: string;
  signupUrl: string;
  listsWithoutKey: boolean;
  needsBaseUrl: boolean;
  needsKey: boolean;
}

/** One model a provider offers. Nulls mean "the provider didn't say" — never a
 *  guessed default, so unknown pricing can't be shown as free. */
export interface ModelOption {
  id: string;
  name: string;
  promptPerMTok: number | null;
  completionPerMTok: number | null;
  context: number | null;
  supportsTools: boolean | null;
}

/** A capability that isn't required, with the cost of its absence. */
export interface ReadinessCheck {
  key: string;
  title: string;
  health: "ok" | "degraded";
  summary: string;
  remedy: string;
}

export interface ConnectionState {
  kind: ProviderKind;
  model: string | null;
  baseUrl: string | null;
  apiKeySet: boolean;
  requiresKey: boolean;
  supportsWebSearch: boolean;
  isComplete: boolean;
}

export interface SetupSnapshot {
  onboarded: boolean;
  connection: ConnectionState;
  providers: ProviderCard[];
  search: { current: SearchState; options: SearchOption[] };
  checks: ReadinessCheck[];
}

export type SearchKind = "searxng" | "openrouter" | "none";

/** One way to search. `available` is false when the option cannot work with the
 *  connection that was just chosen — shown greyed out with a reason, not hidden. */
export interface SearchOption {
  kind: SearchKind;
  label: string;
  blurb: string;
  tradeoff: string;
  requires: string;
  needsUrl: boolean;
  defaultUrl: string;
  available: boolean;
  unavailableBecause: string;
}

export interface SearchState {
  kind: SearchKind;
  searxUrl: string | null;
  endpoint: string | null;
  enabled: boolean;
  costsMoney: boolean;
}

export interface SearchProbeOutcome {
  /** A real search ran and came back with something. */
  working: boolean;
  detail: string;
  hits: number;
}

/** Whether the credential is good — a separate question from reachability, because
 *  OpenRouter's catalogue answers with no key at all. */
export type KeyState = "not_required" | "missing" | "valid" | "rejected";

export interface ProbeOutcome {
  /** We got a model list. Enough to fill the picker, not enough to save. */
  reachable: boolean;
  /** Reached, and holding a credential the provider accepts. Gate "Continue" on this. */
  usable: boolean;
  detail: string;
  models: ModelOption[];
  suggested: string[];
  keyState: KeyState;
  /** Remaining credit, or the provider's own words for why it said no. */
  keyDetail: string;
}

export interface Credentials {
  kind: ProviderKind;
  baseUrl?: string;
  /** Omit to reuse the key already stored for this same endpoint. */
  apiKey?: string;
}

export async function fetchSetup(signal?: AbortSignal): Promise<SetupSnapshot> {
  const response = await fetch("/api/setup", { signal });
  if (!response.ok) throw new Error(`/api/setup returned ${response.status}`);
  return (await response.json()) as SetupSnapshot;
}

/** Try a connection. Never throws for a bad key — an unreachable provider is a
 *  normal answer here, carried in `reachable` and `detail`. */
export async function probeConnection(
  input: Credentials,
  signal?: AbortSignal,
): Promise<ProbeOutcome> {
  const response = await fetch("/api/setup/probe", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(input),
    signal,
  });
  const body = (await response.json()) as ProbeOutcome & { error?: string };
  if (!response.ok) throw new Error(body.error ?? `probe failed (${response.status})`);
  return body;
}

/** Save the connection. Rejects with the server's own sentence, which is written
 *  to be shown to the person who caused it. */
export async function completeSetup(
  input: Credentials & { model: string },
): Promise<{ connection: ConnectionState; warnings: string[] }> {
  const response = await fetch("/api/setup/complete", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(input),
  });
  const body = (await response.json()) as {
    connection: ConnectionState;
    warnings: string[];
    error?: string;
  };
  if (!response.ok) throw new Error(body.error ?? `saving failed (${response.status})`);
  return body;
}

/** Try a search provider. Runs one real search server-side and discards the results,
 *  so the answer is whether it works rather than whether the URL parses. */
export async function probeSearch(
  input: { kind: SearchKind; searxUrl?: string },
  signal?: AbortSignal,
): Promise<SearchProbeOutcome> {
  const response = await fetch("/api/setup/search/probe", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(input),
    signal,
  });
  const body = (await response.json()) as SearchProbeOutcome & { error?: string };
  if (!response.ok) throw new Error(body.error ?? `probe failed (${response.status})`);
  return body;
}

export async function saveSearch(input: {
  kind: SearchKind;
  searxUrl?: string;
}): Promise<SearchState> {
  const response = await fetch("/api/setup/search", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(input),
  });
  const body = (await response.json()) as SearchState & { error?: string };
  if (!response.ok) throw new Error(body.error ?? `saving failed (${response.status})`);
  return body;
}

// -- formatting, shared by the picker and the summary ----------------------- //

/** "$0.30" / "free" / "—". Unknown and free must not look alike. */
export function formatPrice(perMTok: number | null): string {
  if (perMTok === null) return "—";
  if (perMTok === 0) return "free";
  if (perMTok < 0.01) return `$${perMTok.toFixed(4)}`;
  return `$${perMTok.toFixed(2)}`;
}

/** "128K" / "1M" / "1.5M" — a token count nobody wants to read in full.
 *
 * The trailing ".0" is stripped after rounding, not before: 1,000,000 and 1,048,576
 * are the same size to a reader, and showing them as "1M" and "1.0M" in adjacent rows
 * looks like a difference that isn't there.
 */
export function formatContext(tokens: number | null): string {
  if (!tokens) return "—";
  if (tokens >= 1_000_000) {
    return `${(tokens / 1_000_000).toFixed(1).replace(/\.0$/, "")}M`;
  }
  return `${Math.round(tokens / 1000)}K`;
}
